    <?=HTML::style('css/widget_master/embedded_widget_master_template.css')?>
    <?=HTML::style('css/widget_master/flags_widget.css')?>
    <?=HTML::style('css/widget_master/grids.css')?>
    <?=HTML::style('css/widget_master/ie_fix.css')?>
    <?=HTML::script('js/jquery.cycle.all.min.js')?>
    <?=HTML::script('js/jquery.mousewheel.min.js')?>
    <?=HTML::script('js/jquery.scroll.js')?>
</body>
</html>
