<?php namespace Feedback\Entities;

use Helpers\SimpleArray;

class FeedbackNode {
    public $id;    
    public $intname;
    public $firstname;
    public $lastname;
    public $category;
    public $categoryid;
    public $status;
    public $priority;
    public $text;
    public $date;
    public $head_date_format;
    public $daysago;
    public $unix_timestamp;
    public $permission;
    public $rating;
    public $permission_css;
    public $perm_val;
    public $isfeatured;
    public $isflagged;
    public $ispublished;
    public $isarchived;
    public $issticked;
    public $isdeleted;
    public $displayname;
    public $displayimg;
    public $displaycompany;
    public $displayposition;
    public $displayurl;
    public $displaycountry;
    public $displaysbmtdate;
    public $indlock;
    public $contactid;
    public $email;
    public $profilelink;
    public $position;
    public $url;
    public $city;
    public $companyname;
    public $avatar;
    public $siteid;
    public $sitename;
    public $sitedomain;
    public $word_count;
    public $feed_type;
}
